### ISSUE TITLE
no events in subcalender

### ISSUE THREAD

**Issue by ruru4143** [dit-calendar/caldav-telegram-bot#1]
Hello guys, i always get a "no events in subcalender" error.
I installed it like your tutorial with heroku.
I use `/postcalendar dummy-name 2021-01-01` 

My [Baikal](https://sabre.io/baikal/) ([git](https://github.com/sabre-io/Baikal/)) instance and my calender see all 4 events, which are all after 01.01.2021
Display name | Events | Description |  
-- | -- | -- | --
dummy-name | 4 | -

**Comment by boddAH23** [comment]
Hey @ruru4143,
I think the issue might be the calendar name. We forgot to escape the name in the telegram message. I just fixed it. Can you update your bot or rename your calendar (Calendar token ID) to "dummyname" and try it again?

Unfortunately we never tested our bot with other caldav server beside nextcloud, I just tried with baikal and it seems to work. But there might be some problems so don't hesitate to create another issue

**Comment by ruru4143** [comment]
Hey @boddAH23,
I think i make something fundamentally wrong. I recreated the bot and tried the following Username - Calendar token ID combinations:
| Username\Calendartoken-id | test-cal     | testingcal   |
|-----------------------|--------------|--------------|
| user-test-name        | Didin't work | Didin't work |
| testingusername       | Didin't work | Didin't work |

I think the issue is not names. What logs could help you? I can't find any bot-specific logs in heroku. Also my baikal/nginx logs don't look adnormal.

**Comment by boddAH23** [comment]
Hey @ruru4143,
unfortunately we don't have helpful logs yet, but it's on our to-do list. 
But maybe we can help you anyway. 
1. Did you created a new calendar with the calendar token ID "testingusername" for your user?
2. Did you created an event on 01.01.2021
3. Have you used this command in your chat `/postcalendar testingusername 2021-01-01`
4. And you get the error "no events in subcalendar with name testingusername found"?

**Comment by ruru4143** [comment]
@boddAH23 Oh okey, i figured out the problem.
I thought the bot is active reminding you for events, but its only answering the question "is there a event on this day?"
